local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

yandex:
  service: S3
  access_key_id: Rails.application.credentials.dig(:yandex_cloud, :access_key)
  secret_access_key: Rails.application.credentials.dig(:yandex_cloud, :secret_key)
  bucket: Rails.application.credentials.dig(:yandexcloud, :bucket_name)
  region: ru-central1-a
  endpoint: 'https://storage.yandexcloud.net'
  force_path_style: true

# yandex:
#   service: S3
#   access_key_id: ENV['S3_ACCESS_KEY']
#   secret_access_key: ENV['S3_SECRET_KEY']
#   bucket: ENV['S3_BUCKET_NAME']
#   region: ru-central1-a
#   endpoint: 'https://storage.yandexcloud.net'
#   force_path_style: true
